### ISSUE TITLE
Incompatible with Sonoma?

### ISSUE THREAD

**Issue by ahaghgoo** [jordicl/launchbar-menubar-search#7]
I may be quick with this, but the LaunchBar action is giving me errors since upgrading to Sonoma. I'm wondering if this is a security enabling issue since it's not working on any application.

I also don't know how to locate the specific error in the Console logs as searching for Menubar Search or LaunchBar didn't fetch any results in the Console.app.

Thanks for the consideration!

![275967767-3d75e5fd-c1e0-456e-bfa4-68e798bac4d3](https://github.com/jordicl/launchbar-menubar-search/assets/1308002/21b6b505-ef61-4a5b-87c2-1b07dcb0a47d)

**Comment by aeroechelon** [comment]
Running into a similar issue on Sonoma with this error in the logs:

```
Code 1: /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/psych.rb:456:in `parse': (<unknown>): control characters are not allowed at line 1 column 1 (Psych::SyntaxError)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/psych.rb:456:in `parse_stream'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/psych.rb:390:in `parse'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/psych.rb:277:in `load'
	from menu_items.rb:27:in `generate_items'
	from main.rb:15:in `<main>'
```
